import React, { useState, useContext } from "react";
import { TopBar, ToastContext, Tag } from "../components/PlatformUI.jsx";
import { Wallet, TrendingUp, RefreshCw, Plus, CheckCircle2, Clock, BookOpen, Loader2 } from "lucide-react";
import { useSupabaseQuery } from "../../lib/useSupabaseQuery.js";
import {
  fetchInstructorEarningsSummary,
  fetchInstructorCourseRevenue,
  fetchMyPayoutRequests,
  submitPayoutRequest,
} from "../../lib/api/revenue.js";

const STATUS_TONE = { pending: "warning", approved: "success", paid: "success", rejected: "danger" };

function fmt(v) {
  return Number(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function InstructorEarningsScreen({ mentorId, orgId, orgSelector, currentUserId, userEmail, mentorProfileQuery }) {
  const showToast = useContext(ToastContext);
  const [tab, setTab] = useState("overview");
  const [showPayoutForm, setShowPayoutForm] = useState(false);
  const [payoutAmount, setPayoutAmount] = useState("");
  const [payoutMethod, setPayoutMethod] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const summaryQuery = useSupabaseQuery(
    async () => (mentorId ? fetchInstructorEarningsSummary(mentorId) : null),
    [mentorId]
  );
  const courseRevenueQuery = useSupabaseQuery(
    async () => (mentorId ? fetchInstructorCourseRevenue(mentorId) : []),
    [mentorId]
  );
  const payoutsQuery = useSupabaseQuery(
    async () => (mentorId ? fetchMyPayoutRequests(mentorId) : []),
    [mentorId]
  );

  const summary = summaryQuery.data || { total_gross: 0, total_platform_fee: 0, total_net: 0, enrollment_count: 0 };
  const courses = courseRevenueQuery.data || [];
  const payouts = payoutsQuery.data || [];

  function refresh() {
    summaryQuery.refetch();
    courseRevenueQuery.refetch();
    payoutsQuery.refetch();
  }

  async function handleSubmitPayout() {
    if (!payoutAmount || Number(payoutAmount) <= 0) {
      showToast("Enter a valid payout amount.");
      return;
    }
    if (!payoutMethod.trim()) {
      showToast("Enter your payment method (e.g., bank account, PayPal).");
      return;
    }
    setSubmitting(true);
    try {
      const res = await submitPayoutRequest(mentorId, payoutAmount, payoutMethod);
      if (res.success) {
        showToast("Payout request submitted. Your admin will review it.");
        setShowPayoutForm(false);
        setPayoutAmount("");
        setPayoutMethod("");
        payoutsQuery.refetch();
      } else {
        showToast(res.error || "Could not submit payout request.");
      }
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="ta-fade">
      <TopBar
        title="My Earnings"
        sub="Course revenue attributed to your courses and payout requests"
        orgSelector={orgSelector}
      />
      <div className="ta-content" style={{ display: "flex", flexDirection: "column", gap: 20 }}>

        {/* Hero Banner */}
        <div className="ta-hero-banner anim-fluid-entrance">
          <div className="tai-glow-amber" />
          <div className="ta-hero-inner">
            <div className="ta-hero-text">
              <h1 className="ta-hero-title">Instructor Earnings</h1>
              <p className="ta-hero-desc">
                Track revenue generated by your courses and request payouts from your organization admin.
              </p>
            </div>
            <div className="ta-hero-actions">
              <button
                className="ta-btn ta-btn-outline"
                style={{ height: 36, padding: "0 14px", borderRadius: 8, fontSize: 12.5, display: "inline-flex", alignItems: "center", gap: 6 }}
                onClick={refresh}
              >
                <RefreshCw size={13} /> Refresh
              </button>
              <button
                className="ta-btn ta-btn-primary"
                style={{ height: 36, padding: "0 14px", borderRadius: 8, fontSize: 12.5, display: "inline-flex", alignItems: "center", gap: 6 }}
                onClick={() => { setTab("payouts"); setShowPayoutForm(true); }}
              >
                <Plus size={13} /> Request Payout
              </button>
            </div>
          </div>
        </div>

        {/* Stat Cards */}
        <div className="ta-grid ta-grid-4 anim-stagger">
          {[
            { label: "Gross from your courses", value: summaryQuery.loading ? "…" : `$${fmt(summary.total_gross)}`, hint: "Learner payments" },
            { label: "Platform commission", value: summaryQuery.loading ? "…" : `$${fmt(summary.total_platform_fee)}`, hint: "Deducted by platform" },
            { label: "Net to your org", value: summaryQuery.loading ? "…" : `$${fmt(summary.total_net)}`, hint: "Your org keeps this" },
            { label: "Total enrollments", value: summaryQuery.loading ? "…" : (summary.enrollment_count || 0), hint: "Paid learners" },
          ].map((k) => (
            <div key={k.label} className="ta-card" style={{ padding: "14px 18px", borderRadius: 10 }}>
              <div style={{ fontSize: 11, color: "var(--text-3)", fontWeight: 600 }}>{k.label}</div>
              <div style={{ fontSize: 22, fontWeight: 800, marginTop: 4 }}>{k.value}</div>
              <div style={{ fontSize: 11, color: "var(--text-3)", marginTop: 2 }}>{k.hint}</div>
            </div>
          ))}
        </div>

        {/* Note */}
        <div className="ta-card" style={{ background: "var(--surface-2)", border: "1px solid var(--border)", padding: "12px 16px" }}>
          <div className="ta-row ta-gap8">
            <Wallet size={14} color="var(--text-3)" style={{ marginTop: 2, flexShrink: 0 }} />
            <span style={{ fontSize: 12, color: "var(--text-3)", lineHeight: 1.6 }}>
              Revenue from your paid courses flows to your <strong>organization</strong> (after platform commission). You can request a payout from your organization admin, who approves and processes withdrawals through the Payouts section. Earnings tracking here is informational — it shows what your courses generated, not a personal wallet balance.
            </span>
          </div>
        </div>

        {/* Tabs */}
        <div className="ta-tabs">
          {[
            { k: "overview", label: `My courses (${courses.length})` },
            { k: "payouts", label: `Payout requests (${payouts.length})` },
          ].map((t) => (
            <div key={t.k} className={`ta-tab ${tab === t.k ? "active" : ""}`} onClick={() => setTab(t.k)}>{t.label}</div>
          ))}
        </div>

        {tab === "overview" && (
          <div className="ta-card" style={{ borderRadius: 10 }}>
            <div className="ta-table-wrap">
              <table className="ta-table">
                <thead>
                  <tr>
                    <th>Course</th>
                    <th>Listed Price</th>
                    <th>Paid Enrollments</th>
                    <th>Gross Revenue</th>
                  </tr>
                </thead>
                <tbody>
                  {courseRevenueQuery.loading && (
                    <tr><td colSpan={4} className="ta-empty">Loading…</td></tr>
                  )}
                  {!courseRevenueQuery.loading && courses.length === 0 && (
                    <tr>
                      <td colSpan={4} className="ta-empty">
                        <BookOpen size={26} style={{ opacity: 0.35, display: "block", margin: "0 auto 8px" }} />
                        No paid courses yet. Set a price on a course in Content to start tracking revenue.
                      </td>
                    </tr>
                  )}
                  {courses.map((c) => (
                    <tr key={c.course_id}>
                      <td style={{ fontWeight: 600 }}>{c.course_name}</td>
                      <td>
                        {c.listed_price > 0
                          ? <Tag tone="primary">${fmt(c.listed_price)}</Tag>
                          : <Tag tone="neutral">Free</Tag>}
                      </td>
                      <td style={{ fontWeight: 700 }}>{c.enrollment_count}</td>
                      <td style={{ fontWeight: 800, color: "var(--success)" }}>${fmt(c.gross_revenue)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {tab === "payouts" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {/* Request Payout Form */}
            {showPayoutForm && (
              <div className="ta-card" style={{ borderRadius: 10, border: "2px solid var(--primary)" }}>
                <div className="ta-label" style={{ margin: "0 0 12px" }}>New Payout Request</div>
                <div className="ta-grid ta-grid-2 ta-gap12">
                  <div>
                    <div className="ta-label">Amount</div>
                    <input
                      className="ta-input ta-mt6"
                      style={{ width: "100%", boxSizing: "border-box" }}
                      type="number"
                      min="1"
                      placeholder="e.g. 500"
                      value={payoutAmount}
                      onChange={(e) => setPayoutAmount(e.target.value)}
                    />
                  </div>
                  <div>
                    <div className="ta-label">Payment method</div>
                    <input
                      className="ta-input ta-mt6"
                      style={{ width: "100%", boxSizing: "border-box" }}
                      placeholder="e.g. GTBank 0123456789, PayPal email..."
                      value={payoutMethod}
                      onChange={(e) => setPayoutMethod(e.target.value)}
                    />
                  </div>
                </div>
                <div className="ta-row ta-gap8 ta-mt12">
                  <button
                    className="ta-btn ta-btn-primary"
                    disabled={submitting}
                    onClick={handleSubmitPayout}
                  >
                    {submitting ? <><Loader2 size={13} className="ta-spin" /> Submitting…</> : <><CheckCircle2 size={13} /> Submit Request</>}
                  </button>
                  <button
                    className="ta-btn ta-btn-outline"
                    disabled={submitting}
                    onClick={() => setShowPayoutForm(false)}
                  >
                    Cancel
                  </button>
                </div>
                <div style={{ fontSize: 11.5, color: "var(--text-3)", marginTop: 8 }}>
                  Your admin will review this request and process payment outside the platform, then mark it as paid.
                </div>
              </div>
            )}

            {!showPayoutForm && (
              <button
                className="ta-btn ta-btn-outline"
                style={{ alignSelf: "flex-start" }}
                onClick={() => setShowPayoutForm(true)}
              >
                <Plus size={14} /> Request Payout
              </button>
            )}

            {/* Payout history */}
            <div className="ta-card" style={{ borderRadius: 10 }}>
              <div className="ta-table-wrap">
                <table className="ta-table">
                  <thead>
                    <tr>
                      <th>Amount</th>
                      <th>Method</th>
                      <th>Status</th>
                      <th>Requested</th>
                      <th>Processed</th>
                    </tr>
                  </thead>
                  <tbody>
                    {payoutsQuery.loading && (
                      <tr><td colSpan={5} className="ta-empty">Loading…</td></tr>
                    )}
                    {!payoutsQuery.loading && payouts.length === 0 && (
                      <tr>
                        <td colSpan={5} className="ta-empty">
                          <Clock size={24} style={{ opacity: 0.35, display: "block", margin: "0 auto 8px" }} />
                          No payout requests yet.
                        </td>
                      </tr>
                    )}
                    {payouts.map((p) => (
                      <tr key={p.id}>
                        <td style={{ fontWeight: 700 }}>{Number(p.amount).toLocaleString()}</td>
                        <td>{p.payment_method || "—"}</td>
                        <td><Tag tone={STATUS_TONE[p.status] || "warning"}>{p.status}</Tag></td>
                        <td>{p.requested_at ? new Date(p.requested_at).toLocaleDateString() : "—"}</td>
                        <td>{p.processed_at ? new Date(p.processed_at).toLocaleDateString() : "—"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default InstructorEarningsScreen;
