-- Reliable demo scheduling and calendar delivery metadata.

ALTER TABLE public.demo_requests
  ADD COLUMN IF NOT EXISTS calendar_event_id text,
  ADD COLUMN IF NOT EXISTS calendar_event_url text,
  ADD COLUMN IF NOT EXISTS meeting_url text,
  ADD COLUMN IF NOT EXISTS calendar_status text NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS calendar_error text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.demo_booking_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_hash text NOT NULL,
  ip_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_demo_booking_attempts_email_created
  ON public.demo_booking_attempts (email_hash, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_booking_attempts_ip_created
  ON public.demo_booking_attempts (ip_hash, created_at DESC);

ALTER TABLE public.demo_booking_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.demo_booking_attempts FROM anon, authenticated;
GRANT ALL ON public.demo_booking_attempts TO service_role;

-- Public clients must use the booking Edge Function. It validates input,
-- reserves the slot atomically, creates the Calendar event, and only then
-- reports success.
DROP POLICY IF EXISTS "demo_requests_public_insert" ON public.demo_requests;
REVOKE INSERT ON public.demo_requests FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.reserve_demo_appointment(
  p_id uuid,
  p_full_name text,
  p_work_email text,
  p_company_name text,
  p_team_size text,
  p_message text,
  p_source text,
  p_scheduled_date date,
  p_scheduled_time text,
  p_org_type text,
  p_timezone text,
  p_utm_source text DEFAULT NULL,
  p_utm_medium text DEFAULT NULL,
  p_utm_campaign text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(p_scheduled_date::text || '|' || p_scheduled_time));

  IF EXISTS (
    SELECT 1
    FROM public.demo_requests
    WHERE scheduled_date = p_scheduled_date
      AND scheduled_time = p_scheduled_time
      AND status NOT IN ('cancelled', 'closed')
  ) THEN
    RAISE EXCEPTION 'DEMO_SLOT_UNAVAILABLE' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.demo_requests (
    id, full_name, work_email, company_name, team_size, message, source,
    status, scheduled_date, scheduled_time, org_type, timezone,
    calendar_status, utm_source, utm_medium, utm_campaign
  ) VALUES (
    p_id, p_full_name, p_work_email, p_company_name, p_team_size, p_message, p_source,
    'scheduled', p_scheduled_date, p_scheduled_time, p_org_type, p_timezone,
    'creating', p_utm_source, p_utm_medium, p_utm_campaign
  );

  RETURN p_id;
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_demo_appointment(
  uuid, text, text, text, text, text, text, date, text, text, text, text, text, text
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_demo_appointment(
  uuid, text, text, text, text, text, text, date, text, text, text, text, text, text
) TO service_role;

